const uid = (prefix, index) => `${prefix}-${index + 1}`;

const SECTOR_META = {
  trabalhista: { label: 'Trabalhista', moduleKey: 'trabalhista' },
  fiscal: { label: 'Fiscal', moduleKey: 'fiscal' },
  financeiro: { label: 'Financeiro', moduleKey: 'financeiro' },
  societario: { label: 'Societario', moduleKey: 'contadores' },
  atendimento: { label: 'Atendimento', moduleKey: 'atendimento' },
};

const CHECKLIST_BASE = [
  'Documento de identificacao do solicitante',
  'CNPJ e razao social da empresa',
  'Periodo de referencia da solicitacao',
];

const CHECKLIST_BY_SECTOR = {
  trabalhista: [
    'Dados do colaborador (nome, CPF, cargo e data de admissao)',
    'Folha ou evento trabalhista relacionado ao pedido',
  ],
  fiscal: [
    'Notas fiscais do periodo (entrada e saida)',
    'Relatorios de faturamento e impostos anteriores',
  ],
  financeiro: [
    'Extratos bancarios e comprovantes financeiros do periodo',
    'Plano de contas e centro de custo relacionado',
  ],
  societario: [
    'Contrato social e ultimas alteracoes',
    'Documentos dos socios responsaveis',
  ],
  atendimento: [
    'Historico de atendimento do cliente',
    'Descricao formal da demanda solicitada',
  ],
};

const SERVICE_CATALOG = [
  { nome: 'Simulacao de ferias', setor: 'trabalhista' },
  { nome: 'Calculo de rescisao', setor: 'trabalhista' },
  { nome: 'Admissao de colaborador', setor: 'trabalhista' },
  { nome: 'Demissao de colaborador', setor: 'trabalhista' },
  { nome: 'Envio de folha mensal', setor: 'trabalhista' },
  { nome: 'Ajuste de ponto e horas extras', setor: 'trabalhista' },
  { nome: 'Calculo de 13 salario', setor: 'trabalhista' },
  { nome: 'Simulacao de pro-labore', setor: 'trabalhista' },
  { nome: 'Regularizacao de eSocial', setor: 'trabalhista' },
  { nome: 'Emissao de guias de FGTS', setor: 'trabalhista' },

  { nome: 'Apuracao mensal do Simples Nacional', setor: 'fiscal' },
  { nome: 'Emissao de DAS', setor: 'fiscal' },
  { nome: 'Entrega de DEFIS', setor: 'fiscal' },
  { nome: 'Escrituracao fiscal mensal', setor: 'fiscal' },
  { nome: 'Revisao de NFS-e emitidas', setor: 'fiscal' },
  { nome: 'Analise de credito tributario', setor: 'fiscal' },
  { nome: 'Retificacao de obrigacao fiscal', setor: 'fiscal' },
  { nome: 'Parcelamento de debitos fiscais', setor: 'fiscal' },
  { nome: 'Consulta de divida ativa', setor: 'fiscal' },
  { nome: 'Baixa de pendencia fiscal municipal', setor: 'fiscal' },
  { nome: 'Baixa de pendencia fiscal estadual', setor: 'fiscal' },
  { nome: 'Acompanhamento de malha fiscal', setor: 'fiscal' },
  { nome: 'Regularizacao de inscricao estadual', setor: 'fiscal' },
  { nome: 'Reenquadramento tributario', setor: 'fiscal' },
  { nome: 'Analise de anexo do Simples', setor: 'fiscal' },

  { nome: 'Conciliacao bancaria mensal', setor: 'financeiro' },
  { nome: 'Implantacao de fluxo de caixa', setor: 'financeiro' },
  { nome: 'Organizacao de contas a pagar', setor: 'financeiro' },
  { nome: 'Organizacao de contas a receber', setor: 'financeiro' },
  { nome: 'Projecao financeira trimestral', setor: 'financeiro' },
  { nome: 'Analise de inadimplencia', setor: 'financeiro' },
  { nome: 'Emissao de relatorio gerencial financeiro', setor: 'financeiro' },
  { nome: 'Cadastro de plano de contas', setor: 'financeiro' },
  { nome: 'Revisao de precificacao de servicos', setor: 'financeiro' },
  { nome: 'Controle de custos fixos e variaveis', setor: 'financeiro' },
  { nome: 'Renegociacao de dividas com fornecedores', setor: 'financeiro' },
  { nome: 'Analise de ponto de equilibrio operacional', setor: 'financeiro' },
  { nome: 'Estruturacao de politica de desconto comercial', setor: 'financeiro' },
  { nome: 'Conferencia de tarifas e custos bancarios', setor: 'financeiro' },
  { nome: 'Implantacao de rotina de fechamento financeiro mensal', setor: 'financeiro' },
  { nome: 'Revisao de contratos financeiros recorrentes', setor: 'financeiro' },
  { nome: 'Analise de margem por produto ou servico', setor: 'financeiro' },
  { nome: 'Planejamento de pagamentos sazonais', setor: 'financeiro' },
  { nome: 'Estruturacao de politica de credito para clientes', setor: 'financeiro' },
  { nome: 'Monitoramento de indicadores de liquidez', setor: 'financeiro' },
  { nome: 'Consolidacao financeira de grupo empresarial', setor: 'financeiro' },
  { nome: 'Revisao de cronograma de recebiveis', setor: 'financeiro' },
  { nome: 'Mapeamento de despesas nao recorrentes', setor: 'financeiro' },
  { nome: 'Analise de viabilidade para investimento', setor: 'financeiro' },
  { nome: 'Controle de adiantamentos e reembolsos', setor: 'financeiro' },

  { nome: 'Abertura de empresa', setor: 'societario' },
  { nome: 'Alteracao contratual', setor: 'societario' },
  { nome: 'Inclusao de atividade CNAE', setor: 'societario' },
  { nome: 'Baixa de empresa', setor: 'societario' },
  { nome: 'Transformacao de natureza juridica', setor: 'societario' },
  { nome: 'Mudanca de endereco empresarial', setor: 'societario' },
  { nome: 'Emissao de certificado digital', setor: 'societario' },
  { nome: 'Renovacao de certificado digital', setor: 'societario' },
  { nome: 'Regularizacao cadastral na Receita', setor: 'societario' },
  { nome: 'Atualizacao de dados na prefeitura', setor: 'societario' },

  { nome: 'Onboarding de cliente novo', setor: 'atendimento' },
  { nome: 'Atualizacao cadastral de cliente', setor: 'atendimento' },
  { nome: 'Atendimento consultivo mensal', setor: 'atendimento' },
  { nome: 'Reuniao de fechamento mensal', setor: 'atendimento' },
  { nome: 'Encaminhamento de duvida tecnica', setor: 'atendimento' },
  { nome: 'Abertura de chamado prioritario', setor: 'atendimento' },
  { nome: 'Reativacao de cliente inativo', setor: 'atendimento' },
  { nome: 'Revisao de pendencias documentais', setor: 'atendimento' },
  { nome: 'Atendimento para regularizacao urgente', setor: 'atendimento' },
  { nome: 'Validacao de documentacao para fiscalizacao', setor: 'atendimento' },
  { nome: 'Acompanhamento de protocolo externo', setor: 'atendimento' },
  { nome: 'Atualizacao de canais de contato do cliente', setor: 'atendimento' },
  { nome: 'Gestao de retorno de solicitacao tecnica', setor: 'atendimento' },
  { nome: 'Atendimento para alteracao de plano de servicos', setor: 'atendimento' },
  { nome: 'Intermediacao de aprovacao de O.S.', setor: 'atendimento' },
  { nome: 'Tratativa de contestacao de cobranca', setor: 'atendimento' },
  { nome: 'Acompanhamento de entrega com SLA', setor: 'atendimento' },
  { nome: 'Roteiro de atendimento para auditoria interna', setor: 'atendimento' },
  { nome: 'Analise inicial de risco do cliente', setor: 'atendimento' },
  { nome: 'Atendimento de pos-entrega e satisfacao', setor: 'atendimento' },
  { nome: 'Diagnostico comercial contábil inicial', setor: 'comercial' },
  { nome: 'Proposta comercial para migração de contador', setor: 'comercial' },
  { nome: 'Estruturação de escopo para BPO financeiro', setor: 'comercial' },
  { nome: 'Negociação de pacote fiscal e trabalhista', setor: 'comercial' },
  { nome: 'Revisão comercial de honorários e margem', setor: 'comercial' },
  { nome: 'Apresentação de proposta para abertura de empresa', setor: 'comercial' },
  { nome: 'Upsell de consultoria tributária recorrente', setor: 'comercial' },
  { nome: 'Campanha comercial para regularização fiscal', setor: 'comercial' },
  { nome: 'Qualificação de lead para folha de pagamento', setor: 'comercial' },
  { nome: 'Oferta de compliance contábil para grupos empresariais', setor: 'comercial' },
  { nome: 'Renovação contratual com revisão de serviços', setor: 'comercial' },
  { nome: 'Proposta de implantação de indicadores gerenciais', setor: 'comercial' },
  { nome: 'Plano comercial para recuperação de clientes inativos', setor: 'comercial' },
  { nome: 'Estratégia de proposta para empresas do Simples Nacional', setor: 'comercial' },
  { nome: 'Conversão de reunião consultiva em contrato contábil', setor: 'comercial' },
  { nome: 'Revisão fiscal de documentos de entrada e saída', setor: 'fiscal' },
  { nome: 'Conferência de apuração de ICMS mensal', setor: 'fiscal' },
  { nome: 'Conferência de apuração de PIS e COFINS', setor: 'fiscal' },
  { nome: 'Preparação fiscal para fechamento mensal', setor: 'fiscal' },
  { nome: 'Validação fiscal de notas com CFOP crítico', setor: 'fiscal' },
  { nome: 'Retificação de declaração fiscal periódica', setor: 'fiscal' },
  { nome: 'Diagnóstico de pendências fiscais em malha', setor: 'fiscal' },
  { nome: 'Levantamento fiscal para parcelamento de débitos', setor: 'fiscal' },
  { nome: 'Análise de risco tributário por operação', setor: 'fiscal' },
  { nome: 'Revisão de benefícios fiscais aplicáveis', setor: 'fiscal' },
  { nome: 'Implantação de rotina fiscal para novas filiais', setor: 'fiscal' },
  { nome: 'Atualização de cadastro fiscal em órgãos públicos', setor: 'fiscal' },
  { nome: 'Conferência fiscal para mudança de regime tributário', setor: 'fiscal' },
  { nome: 'Auditoria fiscal preventiva trimestral', setor: 'fiscal' },
  { nome: 'Regularização fiscal de empresa sem movimento', setor: 'fiscal' },
  { nome: 'Planejamento trabalhista para fechamento de folha', setor: 'trabalhista' },
  { nome: 'Conferência de eventos periódicos do eSocial', setor: 'trabalhista' },
  { nome: 'Validação de encargos de INSS e FGTS', setor: 'trabalhista' },
  { nome: 'Revisão de cálculo de férias coletivas', setor: 'trabalhista' },
  { nome: 'Revisão de cálculo de 13 salário complementar', setor: 'trabalhista' },
  { nome: 'Regularização de inconsistências de ponto eletrônico', setor: 'trabalhista' },
  { nome: 'Acompanhamento de admissão com checklist completo', setor: 'trabalhista' },
  { nome: 'Acompanhamento de demissão e homologação', setor: 'trabalhista' },
  { nome: 'Revisão de pró-labore e encargos de sócios', setor: 'trabalhista' },
  { nome: 'Implantação de rotina de SST para eSocial', setor: 'trabalhista' },
  { nome: 'Diagnóstico trabalhista para passivos ocultos', setor: 'trabalhista' },
  { nome: 'Conferência de convenções coletivas aplicáveis', setor: 'trabalhista' },
  { nome: 'Adequação de jornadas e banco de horas', setor: 'trabalhista' },
  { nome: 'Regularização de afastamentos e benefícios previdenciários', setor: 'trabalhista' },
  { nome: 'Auditoria trabalhista preventiva semestral', setor: 'trabalhista' },
  { nome: 'Planejamento financeiro mensal com base contábil', setor: 'financeiro' },
  { nome: 'Revisão de fluxo de caixa projetado', setor: 'financeiro' },
  { nome: 'Conciliação de recebimentos por competência', setor: 'financeiro' },
  { nome: 'Conciliação de pagamentos por centro de custo', setor: 'financeiro' },
  { nome: 'Implantação de política de cobrança recorrente', setor: 'financeiro' },
  { nome: 'Análise de inadimplência com plano de ação', setor: 'financeiro' },
  { nome: 'Estruturação de DRE gerencial mensal', setor: 'financeiro' },
  { nome: 'Revisão de precificação baseada em margem de contribuição', setor: 'financeiro' },
  { nome: 'Controle financeiro para empresas do Simples Nacional', setor: 'financeiro' },
  { nome: 'Acompanhamento de contas a pagar estratégicas', setor: 'financeiro' },
  { nome: 'Acompanhamento de contas a receber estratégicas', setor: 'financeiro' },
  { nome: 'Planejamento de capital de giro', setor: 'financeiro' },
  { nome: 'Diagnóstico de custos fixos e variáveis', setor: 'financeiro' },
  { nome: 'Revisão de orçamento versus realizado', setor: 'financeiro' },
  { nome: 'Auditoria financeira preventiva trimestral', setor: 'financeiro' },
];

const buildChecklist = (sectorKey) => {
  const specific = CHECKLIST_BY_SECTOR[sectorKey] || [];
  return [...CHECKLIST_BASE, ...specific];
};

const buildTask = (descricao, ordem, observacoes = '') => ({
  id: `${ordem}-${descricao.toLowerCase().replace(/\s+/g, '-')}`,
  descricao,
  ordem,
  observacoes,
});

const buildTemplate = (item, index) => {
  const sector = SECTOR_META[item.setor] || SECTOR_META.atendimento;
  const checklist = buildChecklist(item.setor);
  const checklistText = checklist.map((doc) => `- ${doc}`).join('; ');

  return {
    id: uid('proc-model', index),
    nome: item.nome,
    descricao: `Modelo padrao para ${item.nome.toLowerCase()} com triagem comercial/atendimento, validacao financeira e execucao setorial.`,
    setorInicial: 'Atendimento',
    setorDestino: sector.label,
    alocacaoColaboradores: [
      { setor: 'Atendimento', modulo: 'atendimento', colaboradores: [] },
      { setor: 'Financeiro', modulo: 'financeiro', colaboradores: [] },
      { setor: sector.label, modulo: sector.moduleKey, colaboradores: [] },
    ],
    etapas: [
      {
        id: uid(`et-${index + 1}`, 0),
        nome: 'Triagem inicial do atendimento',
        setorResponsavel: 'Atendimento',
        moduloResponsavel: 'atendimento',
        ordem: 1,
        tarefas: [
          buildTask('Registrar solicitacao do cliente e validar escopo', 1),
          buildTask('Verificar se o servico esta incluso na assinatura do cliente', 2),
          buildTask('Validar adimplencia do cliente', 3),
          buildTask('Solicitar documentacao obrigatoria ao cliente', 4, `Checklist: ${checklistText}`),
        ],
      },
      {
        id: uid(`et-${index + 1}`, 1),
        nome: 'Validacao comercial/financeira',
        setorResponsavel: 'Financeiro',
        moduloResponsavel: 'financeiro',
        ordem: 2,
        tarefas: [
          buildTask('Se servico nao incluso no plano, emitir O.S. com valor', 1),
          buildTask('Se cliente inadimplente, orientar regularizacao antes da execucao', 2),
          buildTask('Retornar status financeiro para o atendimento', 3),
        ],
      },
      {
        id: uid(`et-${index + 1}`, 2),
        nome: 'Aprovacao do cliente',
        setorResponsavel: 'Atendimento',
        moduloResponsavel: 'atendimento',
        ordem: 3,
        tarefas: [
          buildTask('Encaminhar O.S. e condicoes para aprovacao do cliente', 1),
          buildTask('Registrar aprovacao formal no chamado/protocolo', 2),
          buildTask('Se servico incluso no plano, encaminhar direto ao setor executor', 3),
        ],
      },
      {
        id: uid(`et-${index + 1}`, 3),
        nome: `Execucao tecnica - ${sector.label}`,
        setorResponsavel: sector.label,
        moduloResponsavel: sector.moduleKey,
        ordem: 4,
        tarefas: [
          buildTask(`Executar servico de ${item.nome.toLowerCase()} conforme procedimento interno`, 1),
          buildTask('Conferir qualidade tecnica e evidencias de execucao', 2),
          buildTask('Devolver resultado para o atendimento com parecer final', 3),
        ],
      },
      {
        id: uid(`et-${index + 1}`, 4),
        nome: 'Entrega e encerramento',
        setorResponsavel: 'Atendimento',
        moduloResponsavel: 'atendimento',
        ordem: 5,
        tarefas: [
          buildTask('Apresentar resultado ao cliente e orientar proximos passos', 1),
          buildTask('Registrar aceite do cliente e anexar comprovantes', 2),
          buildTask('Encerrar processo e atualizar indicadores internos', 3),
        ],
      },
    ],
  };
};

export const accountingServiceProcessModels = SERVICE_CATALOG.map(buildTemplate);
